/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[12.353, 2.751, 5.256]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[12.353, 2.899, 3.368]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key001_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key001_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[14.226, 2.751, 5.256]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key002_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key002_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[10.474, 2.751, 5.256]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key003_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key003_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[14.707, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key004_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key004_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[14.707, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key005_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key005_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[14.707, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key006_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key006_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[14.707, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key007_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key007_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[10.769, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key009_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key009_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[7.71, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key008_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key008_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[7.229, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key010_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key010_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[9.136, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key011_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key011_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[11.47, 3.181, -0.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key012_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key012_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[9.315, 2.923, 2.91]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key013_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key013_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[10.996, 3.314, -2.725]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key014_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key014_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[8.185, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key015_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key015_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[6.29, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key016_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key016_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[4.368, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key017_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key017_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[11.971, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key018_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key018_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[9.631, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key019_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key019_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[7.726, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key020_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key020_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[5.817, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key021_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key021_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[3.919, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key022_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key022_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[1.487, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes['Key023_Key-LightestBlue_0'].geometry}
            material={materials['Key-LightestBlue']}
          />
          <mesh
            geometry={nodes.Key023_Outline_LightBlue_0.geometry}
            material={materials.Outline_LightBlue}
          />
        </group>
        <group
          position={[5.808, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key024_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key024_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[3.881, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key025_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key025_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[1.972, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key026_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key026_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[0.071, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key027_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key027_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[6.794, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key028_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key028_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[1.039, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key029_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key029_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[2.953, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key030_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key030_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[4.889, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key031_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key031_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[6.205, 2.789, 4.77]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key032_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key032_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[4.353, 2.789, 4.77]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key033_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key033_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[8.058, 2.789, 4.77]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key034_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key034_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-4.216, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key035_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key035_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-2.318, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key036_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key036_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-0.4, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key037_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key037_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[1.495, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key038_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key038_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[3.403, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key039_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key039_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[5.314, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key040_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key040_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-9.005, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key041_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key041_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-7.099, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key042_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key042_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-5.178, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key043_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key043_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-3.272, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key044_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key044_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-1.365, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key045_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key045_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[0.541, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key046_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key046_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[2.453, 3.313, -2.726]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key047_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key047_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-10.426, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key048_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key048_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-8.532, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key049_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key049_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-6.655, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key050_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key050_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-4.207, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key051_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key051_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-2.31, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key052_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key052_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-0.411, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key053_Key_MidBlue_0.geometry}
            material={materials.Key_MidBlue}
          />
          <mesh
            geometry={nodes.Key053_Outline_MidBlue_0.geometry}
            material={materials.Outline_MidBlue}
          />
        </group>
        <group
          position={[-12.298, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key054_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key054_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-14.708, 3.475, -5.037]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key055_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key055_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-10.889, 3.313, -2.725]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key056_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key056_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-12.78, 3.313, -2.725]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key057_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key057_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-14.671, 3.313, -2.725]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key058_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key058_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-11.841, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key059_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key059_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-6.116, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key060_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key060_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-8.026, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key061_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key061_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-9.94, 3.181, -0.879]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key062_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key062_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-11.337, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key063_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key063_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-10.389, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key064_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key064_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-9.431, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key065_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key065_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-8.492, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key066_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key066_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-7.512, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key067_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key067_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-6.588, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key068_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key068_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-5.611, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key069_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key069_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-4.692, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key070_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key070_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-3.725, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key071_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key071_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-2.794, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key072_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key072_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-1.813, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key073_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key073_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-0.865, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key074_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key074_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-2.525, 2.789, 4.77]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key075_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key075_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-13.451, 2.923, 2.912]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key076_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key076_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-13.926, 3.043, 1.026]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key077_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key077_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-14.2, 3.181, -0.88]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[98.21, 100, 100]}
        >
          <mesh
            geometry={nodes.Key078_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key078_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-9.677, 2.789, 4.77]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key079_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key079_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-12.05, 2.789, 4.77]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key080_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key080_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[-14.416, 2.789, 4.77]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Key081_Key_DarkBlue_0.geometry}
            material={materials.Key_DarkBlue}
          />
          <mesh
            geometry={nodes.Key081_Outline_DarkBlue_0.geometry}
            material={materials.Outline_DarkBlue}
          />
        </group>
        <group
          position={[0.006, 1.834, -0.028]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.KB_Base_Keyboard_0.geometry}
            material={materials.Keyboard}
          />
          <mesh
            geometry={nodes.KB_Base_Outline_Gray_0.geometry}
            material={materials.Outline_Gray}
          />
        </group>
        <group
          position={[14.704, 3.174, -5.013]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Knob_Keyboard_0.geometry}
            material={materials.Keyboard}
          />
          <mesh
            geometry={nodes.Knob_Outline_Gray_0.geometry}
            material={materials.Outline_Gray}
          />
        </group>
        <group
          position={[-31.021, -0.334, 12.101]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Hexagon_Desk_Hexagons_Paint_0.geometry}
            material={materials.Hexagons_Paint}
          />
          <mesh
            geometry={nodes.Hexagon_Desk_Outline_0.geometry}
            material={materials.Outline}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
